version: "3"
services:
    react:
        image: react
        stdin_open: true
        ports:
            - "3000:3000"
        networks:
            - crud-app
    server:
        image: server
        ports:
            - "8000:8000"
        networks:
            - crud-app
        depends_on:
            - mongo
    mongo:
        image: mongo:3.6.19-xenial
        ports:
            - "27017:27017"
        networks:
            - crud-app
        volumes:
            - db:/data/db
networks:
    crud-app:
        driver: bridge
volumes:
    db:
        driver: local        